#!/bin/bash
local_branch="$(git rev-parse --abbrev-ref HEAD)"
echo $local_branch
valid_branch_regex='(feature|fix|bug|hotfix)\/[0-9]+\_[a-z]+(\-[a-z]+)*$'

message="Something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if ! [[  $local_branch  =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi